### ISSUE TITLE
Intake Arm

### ISSUE THREAD

**Issue by Shamrock-Frost** [IronRiders/StrongholdRobot#17]
The intake arm does not appear to be implemented. If this was added, please close this issue with the location in our code.

**Comment by imp-lux** [comment]
Ummm I believe that we no longer have a physical intake arm. Perhaps we should speak with hardware about this tomorrow.

**Comment by imp-lux** [comment]
Yeah so it looks like Design may be hoping to add one more lifting type of mechanism, but it probably would be for the second weekend of competitions, so we don't have to worry about it quite yet.

**Comment by imp-lux** [comment]
The lift mechanism was working at some point.
